version: '3.6'

services:
  register1:
    # image: auth-app
    build: ./
    ports:
      - 8005:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=fuaddauf

  db:
    restart: always
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=fuaddauf
    ports:
      - 5436:5432

volumes: 
  postgres_data: